<?php 
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Wp_Restaurant_Options {
    private $wp_restaurant_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'wp_restaurant_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'wp_restaurant_page_init' ) );
    }

    public function wp_restaurant_add_plugin_page() {
        add_menu_page(
            'WP Restaurant', // page_title
            'WP Restaurant', // menu_title
            'manage_options', // capability
            'wp-restaurant', // menu_slug
            array( $this, 'wp_restaurant_create_admin_page' ), // function
            'dashicons-admin-home', // icon_url
            5 // position
        );
    }

    public function wp_restaurant_create_admin_page() {
        $this->wp_restaurant_options = get_option( 'wp_restaurant_option_name' ); ?>

        <div class="wrap">
            <h2>WP Restaurant</h2>
            <p>You can manage restaurant options from here.</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                    settings_fields( 'wp_restaurant_option_group' );
                    do_settings_sections( 'wp-restaurant-admin' );
                    submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function wp_restaurant_page_init() {
        register_setting(
            'wp_restaurant_option_group', // option_group
            'wp_restaurant_option_name', // option_name
            array( $this, 'wp_restaurant_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'wp_restaurant_setting_section', // id
            'Settings', // title
            array( $this, 'wp_restaurant_section_info' ), // callback
            'wp-restaurant-admin' // page
        );

        add_settings_field(
            'resturent_location_0', // id
            'Resturent Location', // title
            array( $this, 'resturent_location_0_callback' ), // callback
            'wp-restaurant-admin', // page
            'wp_restaurant_setting_section' // section
        );

        add_settings_field(
            'restaurant_type_1', // id
            'Restaurant Type', // title
            array( $this, 'restaurant_type_1_callback' ), // callback
            'wp-restaurant-admin', // page
            'wp_restaurant_setting_section' // section
        );
    }

    public function wp_restaurant_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['resturent_location_0'] ) ) {
            $sanitary_values['resturent_location_0'] = esc_textarea( $input['resturent_location_0'] );
        }

        if ( isset( $input['restaurant_type_1'] ) ) {
            $sanitary_values['restaurant_type_1'] = $input['restaurant_type_1'];
        }

        return $sanitary_values;
    }

    public function wp_restaurant_section_info() {
        
    }

    public function resturent_location_0_callback() {
        printf(
            '<textarea class="large-text" rows="5" name="wp_restaurant_option_name[resturent_location_0]" id="resturent_location_0">%s</textarea>',
            isset( $this->wp_restaurant_options['resturent_location_0'] ) ? esc_attr( $this->wp_restaurant_options['resturent_location_0']) : ''
        );
    }

    public function restaurant_type_1_callback() {
        ?> <select name="wp_restaurant_option_name[restaurant_type_1]" id="restaurant_type_1">
            <?php $selected = (isset( $this->wp_restaurant_options['restaurant_type_1'] ) && $this->wp_restaurant_options['restaurant_type_1'] === 'small') ? 'selected' : '' ; ?>
            <option value="small" <?php echo $selected; ?>>Small</option>
            <?php $selected = (isset( $this->wp_restaurant_options['restaurant_type_1'] ) && $this->wp_restaurant_options['restaurant_type_1'] === 'medium') ? 'selected' : '' ; ?>
            <option value="medium" <?php echo $selected; ?>>Medium</option>
            <?php $selected = (isset( $this->wp_restaurant_options['restaurant_type_1'] ) && $this->wp_restaurant_options['restaurant_type_1'] === 'large') ? 'selected' : '' ; ?>
            <option value="large" <?php echo $selected; ?>>Large</option>
        </select> <?php
    }

}
if ( is_admin() )
    $wp_restaurant = new Wp_Restaurant_Options();

/* 
 * Retrieve this value with:
 * $wp_restaurant_options = get_option( 'wp_restaurant_option_name' ); // Array of All Options
 * $resturent_location_0 = $wp_restaurant_options['resturent_location_0']; // Resturent Location
 * $restaurant_type_1 = $wp_restaurant_options['restaurant_type_1']; // Restaurant Type
 */
